-- Sensible default batches
INSERT INTO "batches" (
	"name"
) VALUES
	('BBA : Batch 12'),
	('BBA : Batch 13'),
	('BBA : Batch 14'),
	('BBA : Batch 15'),
	('BBA : Batch 16'),
	('BBA : Batch 17'),
	('BBA : Batch 17, 2076'),
	('BBA : Batch 18, 2077'),
	('BBA : Batch 19, 2078'),
	('BBA : Batch 20, 2079'),
	('BBM : Batch 1, 2075'),
	('BBM : Batch 2, 2076'),
	('BBM : Batch 3, 2077'),
	('BBM : Batch 4, 2078'),
	('BBM : Batch 5, 2079'),
	('BBS : Batch 10'),
	('BBS : Batch 11'),
	('BBS : Batch 12'),
	('BBS : Batch 13'),
	('BBS : Batch 14'),
	('BBS : Batch 15'),
	('BBS : Batch 15, 2076'),
	('BBS : Batch 16, 2077'),
	('BBS : Batch 17, 2078'),
	('BBS : Batch 18, 2079'),
	('BBS : Batch 19, 2080'),
	('BBS : Batch 20, 2081'),
	('BCA : Batch 1, 2075'),
	('BCA : Batch 2, 2076'),
	('BCA : Batch 3, 2077'),
	('BCA : Batch 4, 2078'),
	('BCA : Batch 5, 2079'),
	('BIM : Batch 14'),
	('BIM : Batch 15'),
	('BIM : Batch 16'),
	('BIM : Batch 17'),
	('BIM : Batch 18'),
	('BIM : Batch 19'),
	('BIM : Batch 19, 2076'),
	('BIM : Batch 20, 2077'),
	('BIM : Batch 21, 2078'),
	('BIM : Batch 22, 2079'),
	('BScCSIT : 2071'),
	('BScCSIT : 2072'),
	('BScCSIT : 2073'),
	('BScCSIT : 2074'),
	('BScCSIT : 2075'),
	('BScCSIT : 2076'),
	('BScCSIT : 2077'),
	('BScCSIT : 2078'),
	('BScCSIT : 2079'),
	('BScCSIT : 2080'),
	('BscCsit : Batch 11, 2076'),
	('Management : Batch 15, 2072'),
	('Management : Batch 16, 2073'),
	('Management : Batch 17, 2074'),
	('Management : Batch 18, 2075'),
	('Management : Batch 19, 2076'),
	('Management : Batch 20, 2077'),
	('Management : Batch 21, 2078'),
	('Management : Batch 22, 2079'),
	('Management : Batch 23, 2080'),
	('MBS : Batch 2, 2076'),
	('MBS : Batch 3, 2078'),
	('MBS : Batch 4, 2079'),
	('MBS: Batch 1,2075'),
	('Science : Batch 10, 2071'),
	('Science : Batch 11, 2072'),
	('Science : Batch 12, 2073'),
	('Science : Batch 12, 2073'),
	('Science : Batch 13, 2074'),
	('Science : Batch 14, 2075'),
	('Science : Batch 15, 2076'),
	('Science : Batch 16, 2077'),
	('Science : Batch 17, 2078'),
	('Science : Batch 18, 2079'),
	('Science : Batch 19, 2080');

-- Sensible default books
INSERT INTO "books" (
	"title",
	"author",
	"publisher"
) VALUES
	('A PRATICAL BOOK OF ACCOUNTANCY AND AUDITING', 'DHAKAL, RAM KRISHNA | SHAKYA, SHREE RATNA | SINGH, RAKESH | SHAH, GAURI | JHA, SHIVA', 'OXFORD PUBLISHERS AND DISTRIBUTORS'),
	('ACCOUNTANCY AND AUDITING', 'LIMBU, Y.B.', 'RATNA PUSTAK BHANDAR'),
	('ADVANCED ACCOUNTANCY VOL 1', 'MAHESHWARI, SN | MAHESHWARI, SK', 'VIKAS PUBLISHING HOUSE PVT LTD'),
	('SURYA,S ADVANCED CHEMISTRY', 'YADAV, AMAR PRASAD | JHA, VINAT KUMAR', 'SURYA PUBLICATIONS'),
	('ANNOTATED CHECKLIST OF THE FLOWERING PLANTS OF NEPAL', 'PRESS, J.R. | SHRESTHA, K.K. | SUTTON, D.A.', 'THE NATURAL HISTORY MISEUM'),
	('ANMOL DICTIONARY OF CHEMISTRY', 'KAUSHIK, R.K. | YADAV, M.S.', 'ANMOL PUBLICATIONS PVT.LTD'),
	('ANELEMENTARY ECONOMIC THEORY', 'PANERU, SURENDRA', 'BUDDHA ACADEMIC PUBLISHERS AND DISTRIBUTORS PVT. LTD.'),
	('ALGEBRA AND GEOMETRY', 'M.B.SINGH', 'THE TRIBHUVAN UNIVERSITY PRESS'),
	('AAMA KO SAPANA', 'GOPAL PRASAD RIMAL', 'SANJHA PRAKASHAN'),
	('IBM PC ASSEMBLY LANGUAGE AND PROGRAMMING', 'ABEL, PETER', 'PEARSON EDUCATION ASIA'),
	('ANIMALS', 'DISCOVERY CHANNEL', 'POPULAR PRAKASHAN'),
	('ADVANCED PHYSICAL CHEMISTRY', 'RAJ, GURDEEP', 'KRISHNA PRAKASHAN MEDIA(P) LTD'),
	('BANASPATI BIGYAN BOTANY', 'N.N. SINGH', 'NEW BUILDING LAKHNAU'),
	('A BASIC COURSE IN ACCOUNTANCY', 'DANGOL, RATNA MAN | KOIRALA, SHALIK RAM | KHADKA, AJAYA KUMAR | RAI, ISHWOR MAN', 'TALEJU PRAKASHAN'),
	('A BASIC COURSES IN ACCOUNTANCY XII', 'DANGOL, RATNA MAN | KOIRALA, SHALIK RAM', 'TALEJU PUSTAK BITARAK'),
	('BOTANY', 'DUTTA, A.C.', 'OXFORD UNIVERSITY PRESS'),
	('BUSINESS ENVIRONMENT IN NEPAL', 'SHRESTHA, DURGESH KUMAR | PRASAD, GOVINDA', 'DHAULAGIRI BOOKS AND STATIONERY'),
	('A BOOK ON HOTEL MANAGEMENT', 'OLI, GOPAL SINGH | CHHETRI,B B', 'SHREE NEPAL EDUCATION M.P. PVT. LTD'),
	('A BOOK ON HOTEL MANAGEMENT', 'OLI, GOPAL SINGH | CHHERI, B.B.', 'BUDDHA ACADEMIC PUBLISHERS AND DISTRIBUTORS PVT. LTD.'),
	('BEYOND LOYALTY', 'CHENET, PIERRE | JOHANSEN, JON IVAR', 'PRENTICE-HALL OF INDIA PRIVATE LIMITED'),
	('BASIC MATHEMATICS GRADE XII', 'BAJRACHARYA, D.R.', 'SUKUNDA PUSTAK'),
	('BASIC MATHEMATICS GRADE: XII', 'BAJRACHARYA, D.R. | SHRESHTHA, R.M. | SINGH, M.B. | STHAPIT, Y.R. | BAJRACHARYA, B.C.', 'SUKUNDA PUSTAK BHAWAN'),
	('BIRDS OF NEPAL', 'STAHR, ELVIS J', 'NATURE HIMALAYAS'),
	('BATTLES OF THE NEW REPUBLIC', 'PRASHANT JHA', 'ALEPH BOOK COMPANY'),
	('BUSINESS ORGANIZATION AND MANAGEMENT', 'SHRESTHA, KUL NARSINGH', 'NABIN PRAKASHAN'),
	('BASIC PRICIPLES OF COST ACCOUNTING', 'SHRESTHA, BISHWESHWOR MAN', 'M.K. PUBLISHERS AND DISTRIBUTORS BHOTAHITY, KATHMANDU'),
	('BASANTI', 'RANA DAIMOND SHAMSHER', 'RATNA PUSTAK BHANDAR'),
	('BUSINESS STUDIES', 'SHARMA, M. C.', 'S.CHAND AND COMPANY LTD'),
	('BUSINESS STUDIES', 'PRASAD, NARESH PRASAD | RANJIT, KUMAR KIRAN | JOSHI, RUPENDRA | SHARMA, NARAD PRASAD', 'ACHIEVERS, KATHMANDU'),
	('BUSINESS STUDIES-I GRADE XI', 'PANT, PREM R.', 'BUDDHA PUBLICATION'),
	('BUSINESS STUDIES GRADE XII', 'PANT, HEM R. | GAUTAM, ISHWOR | PANDEY, L P | THAPA, RAJAN BIKRAM | UPADHYAY, PRADYUMNA', 'BUDDHA PUBLICATION'),
	('BUSINESS STATISTICS', 'BAJRACHARYA, B.C.', 'M.K.PUBLISHERS AND DISTRIBUTORS'),
	('BITIYA SUDHAR KARYA DAL, 2059 KO PRATIBEDAN', '', ''),
	('BUSINESS STUDIES PRINCIPLES AND PRACTICE OF MANAGEMENT', 'GUPTA, O.P. | JAIN, S.K.', 'VIKAS PUBLISHING HOUSE PVT LTD'),
	('BIOLOGY XI', 'VERMA, P.S. | PANDEY, B.P.', 'S.CHAND AND COMPANY LTD'),
	('COMMERCIAL ACCOUNT', 'MUNAKARMI, SHIVA PRASAD', 'EDUCATIONAL ENTERPRISE (P) LTD.'),
	('COST ACCOUNTING', 'JAIN, S.P. | NARANG, K.L.', 'KALYANI PUBLISHERS'),
	('COST ACCOUNTING', 'KHAN, M Y | JAIN, P.K.', 'TATA MCGRAW-HILL PUBLISHING COMPANTY LIMITED'),
	('CLIFFS AP BIOLOGY', 'PACK, PHILLIP E.', 'WILEY DREAMTECH INDIA PVT. LTD.'),
	('CLIFFS AP CHEMISTRY', 'THORPE, GARY', 'WILEY DREAMTECH INDIA PVT. LTD.'),
	('CONCEPTS OF BIOLOGY (FOR CLASS XI)', 'MAJUPURIA, TRILOK CHANDRA | KUMAR ROHIT', 'M.DEVI, LASHKAR'),
	('A CLASS BOOK OF BOTANY', 'DUTTA, A.C.', 'OXFORD UNIVERSITY PRESS'),
	('COLLEGE BOTANY VOLUME II', 'GANGULEE, HIRENDRA CHANDRA | KAR, ASOK KUMAR', 'NEW CENTRAL BOOK AGENCY(P) LTD'),
	('COLLEGE CHEMISTRY', 'A.D.MISHRA | ARUN KUMAR SHARMA | THAM NATH ADHIKARI | GIRIJA ARYAL | KHADKA BAHADUR PAL', 'AYAM PUBLICATIONS'),
	('CHEMICAL CALCULATIONS', 'GHOSH, A.K.', 'VIJAY BHAGAT'),
	('COMPUTER', 'MAHESH BIKRAM SHAH', 'FINEPRINT'),
	('COLLEGE CHEMISTRY', 'SHARMA KUMAR ARUN', 'AYAM PUBLICATION AND DISTRIBUTORS PVT.LTD.'),
	('COMPREHENSIVE CHEMISTRY PART -1', 'WAGLEY, PROF. DR. P | LAMA, PC | BHATTARAI, BR | SHARMA, RK | GAUTAM, SD | KHADKA, NM | PANT, M | ADHIKARI, NR', 'KALA BOOKS CENTER PUBLISHER &amp; DISTRIBUTORS'),
	('COMPREHENSIVE CHEMISTRY PART -1', 'WAGLEY, PROF. DR. P | LAMA, PC | BHATTARAI, BR | SHARMA, RK | GAUTAM, SD | KHADKA, NM | PANT, M | ADHIKARI, NR', 'HAJURKO PRAKASHAN'),
	('COMPREHENSIVE CHEMISTRY PART -1', 'GAUTAM, SD | PANT, M | ADHIKARI, NR', 'HERITAGE PUBLISHERS AND DISTRIBUTOR'),
	('COMPREHENSIVE CHEMISTRY PART -2', 'WAGLEY, PROF. DR. P | LAMA, PC | BHATTARAI, BR | SHARMA, RK | GAUTAM, SD | KHADKA, NM | PANT, M | ADHIKARI, NR', 'HAJURKO PRAKASHAN'),
	('COACHING FOR GROWTH', 'BOLT, PETER', 'PRENTICE-HALL OF INDIA PRIVATE LIMITED'),
	('COMPREHENSIVE', 'GAUTAM SD', 'HERITAGE PUBLISHER AND DISTRIBUTOR'),
	('+2 CHEMISTRY VOL.1', 'CHAULAGAIN, MANI RAJ / B.C., TEJ BAHADUR', 'BHRIKUTI PUSTAK'),
	('CAPITAL MARKET IN NEPAL', 'SAPKOTA, PRAKASH CHANDRA', 'CAPITAL MARKET RESEARCH AND DEVELOPMENT P.LTD'),
	('COMPUTER CONCEPT CLASS X', 'KHANAL, R.C.', 'EKTA BOOKS DISTRIBUTORS PVT. LTD'),
	('CONCEPTUAL PHYSICS FOR CLASS XII', 'SHRESTHA G.B.', 'MANICHUD PRAKASHAN'),
	('CONCEPTUAL PHYSICS FOR CLASS XII', 'JAIN, S.K.', 'S.CHAND AND COMPANY LTD.'),
	('CONCEPTS OF PHYSICS PART 1', 'VERMA, H C', 'BHARATI BHAWAN'),
	('CONCEPTS OF PHYSICS PART 2', 'VERMA, H C', 'BHARATI BHAWAN'),
	('COMPUTER PROGRAMMING IN BASIC', 'MYERS, DAVID L. | ELSWICK, VALARIE A. | HOPFENSPERGER, PATRICK W. | PAVLOVICH, JOSEPH P.', 'HOUGHTAN MIFFLIN COMPANY'),
	('A COMPLETE TEXTBOOK OF BIOLOGY CLASS XI', 'K.R.MEHTA', 'SATYAL');

-- Sensible default copies
INSERT INTO "copies" (
	"register_id",
	"book_id"
) VALUES
	('14257', (SELECT "id" FROM "books" ORDER BY random() LIMIT 1)),
	('14260', (SELECT "id" FROM "books" ORDER BY random() LIMIT 1)),
	('14262', (SELECT "id" FROM "books" ORDER BY random() LIMIT 1)),
	('14263', (SELECT "id" FROM "books" ORDER BY random() LIMIT 1)),
	('14258', (SELECT "id" FROM "books" ORDER BY random() LIMIT 1)),
	('14259', (SELECT "id" FROM "books" ORDER BY random() LIMIT 1)),
	('14267', (SELECT "id" FROM "books" ORDER BY random() LIMIT 1)),
	('14268', (SELECT "id" FROM "books" ORDER BY random() LIMIT 1)),
	('14270', (SELECT "id" FROM "books" ORDER BY random() LIMIT 1)),
	('14274', (SELECT "id" FROM "books" ORDER BY random() LIMIT 1)),
	('14275', (SELECT "id" FROM "books" ORDER BY random() LIMIT 1));

-- Sensible default students
INSERT INTO "students" (
	"id_num",
	"name",
	"password_hashed",
	"address",
	"contact",
	"email",
	"batch_id"
) VALUES
	('20-00031-5', 'Safal Piya', '$2a$12$wqhDYurmZ4cbGvylxq.kx..UFU2ZZ1j6nXSrg8tLnPZpDUuR8seGC', 'Samakhusi', '9876543210', 'mrsafalpiya@gmail.com', 49),
	('20-00032-5', 'Raj Bahadur', '$2a$12$wqhDYurmZ4cbGvylxq.kx..UFU2ZZ1j6nXSrg8tLnPZpDUuR8seGC', '', '', '', 38),
	('20-00033-5', 'Ravi Shankar', '$2a$12$wqhDYurmZ4cbGvylxq.kx..UFU2ZZ1j6nXSrg8tLnPZpDUuR8seGC', '', '', '', 49),
	('20-00034-5', 'Suraj Kumar', '$2a$12$wqhDYurmZ4cbGvylxq.kx..UFU2ZZ1j6nXSrg8tLnPZpDUuR8seGC', '', '', '', 54);

-- Sensible default reservations
INSERT INTO "reservations" (
	"book_id",
	"student_id"
) VALUES
	((SELECT "id" FROM "books" ORDER BY random() LIMIT 1), (SELECT "id" FROM "students" ORDER BY random() LIMIT 1)),
	((SELECT "id" FROM "books" ORDER BY random() LIMIT 1), (SELECT "id" FROM "students" ORDER BY random() LIMIT 1));

-- Sensible default transactions
INSERT INTO "transactions" (
	"transaction_type",
	"copy_id",
	"student_id",
	"created_at"
) VALUES
	('borrow', 1, 1, '2022-04-22 07:08:10'),
	('return', 1, 1, '2022-05-12 12:10:32'),
	('borrow', 2, 1, '2022-09-24 09:11:06'),
	('borrow', 3, 1, '2022-10-19 10:13:03'),
	('borrow', 4, 1, '2022-11-10 09:02:10'),
	('return', 2, 1, '2023-01-21 10:09:10'),
	('return', 3, 1, '2023-02-10 12:32:00'),
	('borrow', 5, 1, '2023-02-14 09:07:00'),
	('borrow', 6, 1, '2023-02-15 14:25:00');

INSERT INTO "borrows" (
	"copy_id",
	"student_id",
	"created_at"
) VALUES
	(4, 1, '2022-11-10 09:02:10'),
	(5, 1, '2023-02-14 09:07:00'),
	(6, 1, '2023-02-15 14:25:00');

INSERT INTO "transactions" (
	"transaction_type",
	"copy_id",
	"student_id",
	"created_at"
) VALUES
	('borrow', 1, 3, '2023-02-14 07:08:10');

INSERT INTO "borrows" (
	"copy_id",
	"student_id",
	"created_at"
) VALUES
	(1, 3, '2023-02-14 07:08:10');

INSERT INTO transactions (
	"transaction_type",
	"copy_id",
	"student_id",
	"created_at"
) VALUES
	('borrow', 4, 4, '2022-02-20 02:05:12'),
	('borrow', 5, 4, '2023-02-14 07:08:10');

INSERT INTO "borrows" (
	"copy_id",
	"student_id",
	"created_at"
) VALUES
	(4, 4, '2022-02-20 02:05:12'),
	(5, 4, '2023-02-14 07:08:10');
