// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: copies.sql

package db

import (
	"context"
	"database/sql"
)

const createCopy = `-- name: CreateCopy :one
INSERT INTO copies (
	book_id
) VALUES (
	$1
) RETURNING id, register_id, book_id
`

func (q *Queries) CreateCopy(ctx context.Context, bookID sql.NullInt64) (Copy, error) {
	row := q.db.QueryRowContext(ctx, createCopy, bookID)
	var i Copy
	err := row.Scan(&i.ID, &i.RegisterID, &i.BookID)
	return i, err
}

const deleteCopy = `-- name: DeleteCopy :exec
DELETE FROM copies
WHERE id = $1
`

func (q *Queries) DeleteCopy(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCopy, id)
	return err
}
