// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"database/sql"
	"time"
)

type Batch struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type Book struct {
	ID        int64          `json:"id"`
	Code      string         `json:"code"`
	Title     string         `json:"title"`
	Author    sql.NullString `json:"author"`
	Publisher sql.NullString `json:"publisher"`
}

type Copy struct {
	ID         int64         `json:"id"`
	RegisterID string        `json:"register_id"`
	BookID     sql.NullInt64 `json:"book_id"`
}

type IDType struct {
	ID     int64  `json:"id"`
	IDType string `json:"id_type"`
}

type Profile struct {
	ID      int64          `json:"id"`
	UserID  sql.NullInt64  `json:"user_id"`
	Address sql.NullString `json:"address"`
	City    sql.NullString `json:"city"`
	State   sql.NullString `json:"state"`
	Contact sql.NullString `json:"contact"`
	Email   sql.NullString `json:"email"`
	BatchID sql.NullInt64  `json:"batch_id"`
}

type Reservation struct {
	ID        int64     `json:"id"`
	BookID    int64     `json:"book_id"`
	UserID    int64     `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
}

type Transaction struct {
	ID              int64     `json:"id"`
	TransactionType string    `json:"transaction_type"`
	CopyID          int64     `json:"copy_id"`
	UserID          int64     `json:"user_id"`
	CreatedAt       time.Time `json:"created_at"`
}

type User struct {
	ID             int64         `json:"id"`
	IDTypeID       sql.NullInt64 `json:"id_type_id"`
	IDNum          string        `json:"id_num"`
	Name           string        `json:"name"`
	PasswordHashed string        `json:"password_hashed"`
}
